version: "3.8"
services:
  mysql:
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_PASSWORD: lmsesac
      MYSQL_DATABASE: lmsesac
      MYSQL_USER: lmsesac
      MYSQL_PASSWORD: lmsesac
      TZ: Asia/Seoul
    command:
      - --default-authentication-plugin=mysql_native_password
    ports:
      - "3305:3306"
    restart: always
  # spring:
  #   volumes:
  #     - .:/app/
  #   build:
  #     context: .
  #   ports:
  #     - "8080:8080"